### ISSUE TITLE
[Bug]: Type coverage plugin - Too few arguments to function PHPStan\Analyser\RuleErrorTransformer

### ISSUE THREAD

**Issue by chrisrhymes** [pestphp/pest#1418]
### What Happened

After updating phpstan to 2.1.18 (previously using 2.1.17) I get the below error when trying to run `php artisan test --type-coverage`. I couldn't see an issues tab on the type coverage plugin so am raising here.

```
ArgumentCountError 

  Too few arguments to function PHPStan\Analyser\RuleErrorTransformer::__construct(), 0 passed in /var/www/html/vendor/pestphp/pest-plugin-type-coverage/src/TestCaseForTypeCoverage.php on line 113 and exactly 1 expected

  at phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/RuleErrorTransformer.php:40
     36▕ final class RuleErrorTransformer
     37▕ {
     38▕     private Parser $parser;
     39▕     private Differ $differ;
  ➜  40▕     public function __construct(
     41▕         #[AutowiredParameter('@currentPhpVersionPhpParser')]
     42▕         Parser $parser
     43▕     )
     44▕     {
```

### How to Reproduce

Run `composer update` to update phpstan to 2.1.18 and then run `php artisan test --type-coverage` 

### Pest Version

v3.8.2

### PHP Version

8.4.3

### Operation System

Linux

**Comment by tabatii** [comment]
same error
