### ISSUE TITLE
Higher order tests break after upgrading to v1.8

### ISSUE THREAD

**Issue by jrmajor** [pestphp/pest#343]
Pest v1.8 broke higher order tests for expectations containing string `'It'`.

```php
it('works')->expect('It')->toBe('It');
```

throws the following error:

```
Too few arguments to function Closure::it(), 0 passed in vendor/pestphp/pest/src/Support/Reflection.php on line 60 and at least 1 expected
```

Probably caused by #331 (my guess is that `'it'` is treated as callable, as there is a function with this name).
This test reproduces the problem: a38bfa9416fd3282b5753c38f5795f1b302d00db.
Failing workflow after updating to v1.8: https://github.com/jrmajor/fluent-php/runs/3037574767#step:5:411.

**Comment by jrmajor** [comment]
Fixed by #344, thank you @lukeraymonddowning!
